### ISSUE TITLE
Drag&Drop others objects

### ISSUE THREAD

**Issue by ealoticopve** [w8r/leaflet-labeled-circle#15]
Hello my friend! I am very interested in your plugin! I'm trying to integrate it into my work but I'm not getting it. I would also like to know if it is possible to drag & drop another object that is not a circle-marker, for example, I would like to do it with a semi-circle. The semi-circle is a plugin from another colleague.

- I'm trying to do something like this! I would like to **drag the semi-circle**, **fixed to the red point** (sensor) as your plugin does in the demo.
- In this case, **your circle-marker would be my semi-circle and your Point would be my sensor.**

![80870843-e2720280-8ca0-11ea-8cc6-6adde23912a0](https://user-images.githubusercontent.com/61938096/81443432-4c8d1a80-916d-11ea-80a2-fa4285d46448.jpg)

Could you help me? Thank you!

PS:
[[Semi-Circle Plugin here!]](https://github.com/jieter/Leaflet-semicircle)

**Comment by w8r** [comment]
@ealoticopve Ola! Yes, I think it's possible. But do you need to update the direction and opening angle of your semi-circle while dragging or just drag it altogether?

**Comment by ealoticopve** [comment]
Hello, thanks for the quick response!
I would like to change the direction of the semi-circle only.
Briefly summarizing what I want, it may be better:

I wish the sensor could change the pointing direction. The angle would not be necessary to change it.

An example: The sensor in the photo has a direction (bottom left) and if I wanted to move it to the right, it would be enough to drag & drop the semi-circle, fixed on the sensor, giving the feeling that its pointing direction has been changed.

PS: Sorry for the portuguese message, i forgot to translate it hehe

**Comment by w8r** [comment]
Something like that?
http://spacetime.nypl.org/Leaflet.GeotagPhoto/examples/camera.html
https://github.com/nypl-spacetime/Leaflet.GeotagPhoto

**Comment by ealoticopve** [comment]
Omg, amazing! That's exactly it! 1000 thanks!

**Comment by w8r** [comment]
You're welcome, say hi to Bert, the author, he's a great guy))
