### ISSUE TITLE
Styling is hard coded

### ISSUE THREAD

**Issue by popkinj** [w8r/leaflet-labeled-circle#22]
Thanks for this great plugin ☺
The README shows the ability to change styling of the marker. However, it appears to be hardcoded [here](https://github.com/w8r/leaflet-labeled-circle/blob/master/src/marker.js#L30-L47). Am I not using this tool properly?

If PRs are welcome I don't mind helping out. 

Thanks
Jamie

**Comment by w8r** [comment]
Why, you can pass different set of `markerOptions` etc, you see [here](https://github.com/w8r/leaflet-labeled-circle/blob/master/src/marker.js#L167) it's used from the options passed in to the Control

**Comment by popkinj** [comment]
Thanks @w8r  :)
